version: "3.9"
services:
  db:
    image: postgres:16.6-alpine3.19
    container_name: teste_java_spring_postegres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: teste_java_spring
      POSTGRES_DB: teste_java_spring
      POSTGRES_PASSWORD: 12345

  redis:
    container_name: cache_magic
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  rabbitmq:
    image: "rabbitmq:3.8.6-management-alpine"
    container_name: rabbitmq-project-glue
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  cache:
    driver: local
