version: "3.9"
services:
  db:
    image: postgres
    container_name: teste_java_spring_postegres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: teste_java_spring
      POSTGRES_DB: teste_java_spring
      POSTGRES_PASSWORD: 12345
